#!/usr/bin/env bash
set -euo pipefail
METHOD=${1:-cspd}
export GPUS_PER_NODE=1 TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-1}
export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-2} ROLLOUT_N=${ROLLOUT_N:-2}
export MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-512} MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-256}
export CSPD_TOPK=${CSPD_TOPK:-2} CSPD_PREFIXES=${CSPD_PREFIXES:-2}
export GPU_MEM_UTIL=${GPU_MEM_UTIL:-0.35} VAL_BEFORE_TRAIN=False TEST_FREQ=-1 SAVE_FREQ=-1
export MAX_NUM_SEQS=${MAX_NUM_SEQS:-16}
export AGENT_LOOP_WORKERS=${AGENT_LOOP_WORKERS:-1}
export RAY_NUM_CPUS=${RAY_NUM_CPUS:-4}
export SWANLAB_MODE=disabled EXP_NAME=debug-${METHOD}-${SLURM_JOB_ID:-local}
exec /home/fit/alex1/WORK/Meiqi.Gu/CSPD/scripts/training/run_math_ppo_cspd.sh "${METHOD}"
